title: In Patient Rehab
#logo: relative path to image
description: description goes here
show_download: true
#theme: jekyll-theme-minima
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
