// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EF_StoreProc.Models
{
    public partial class RehabAssessmentCareToolContext : DbContext
    {
        public RehabAssessmentCareToolContext()
        {
        }

        public RehabAssessmentCareToolContext(DbContextOptions<RehabAssessmentCareToolContext> options)
            : base(options)
        {
        }

        public virtual DbSet<VTreatingSpecialtyPatNoName> VTreatingSpecialtyPatNoName { get; set; }
        public virtual DbSet<VTreatingSpecialtyRecent3Yrs> VTreatingSpecialtyRecent3Yrs { get; set; }
        public virtual DbSet<VTreatingSpecialtyRecent3YrsNew> VTreatingSpecialtyRecent3YrsNew { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("VHA20\\VHAPORSUNC");

            modelBuilder.Entity<VTreatingSpecialtyPatNoName>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vTreatingSpecialtyPatNoName", "shared");

                entity.Property(e => e.Admitday)
                    .HasColumnType("datetime")
                    .HasColumnName("admitday");

                entity.Property(e => e.Bedsecn).HasColumnName("bedsecn");

                entity.Property(e => e.Bsta6a)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("bsta6a");

                entity.Property(e => e.CLos).HasColumnName("C_LOS");

                entity.Property(e => e.RealSsn).HasColumnName("RealSSN");

                entity.Property(e => e.ScrSsnt)
                    .HasMaxLength(38)
                    .IsUnicode(false)
                    .HasColumnName("ScrSSNT");

                entity.Property(e => e.Scrnum).HasColumnName("scrnum");

                entity.Property(e => e.Scrssn).HasColumnName("scrssn");
            });

            modelBuilder.Entity<VTreatingSpecialtyRecent3Yrs>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vTreatingSpecialtyRecent3Yrs", "shared");

                entity.Property(e => e.Admitday)
                    .HasColumnType("datetime")
                    .HasColumnName("admitday");

                entity.Property(e => e.Bedsecn).HasColumnName("bedsecn");

                entity.Property(e => e.Bsta6a)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("bsta6a");

                entity.Property(e => e.DoB).HasColumnType("datetime");

                entity.Property(e => e.FirstName)
                    .HasMaxLength(75)
                    .IsUnicode(false)
                    .HasColumnName("First_Name");

                entity.Property(e => e.LastName)
                    .HasMaxLength(60)
                    .IsUnicode(false)
                    .HasColumnName("Last_Name");

                entity.Property(e => e.PatientIcn)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("PatientICN");

                entity.Property(e => e.PatientName)
                    .HasMaxLength(120)
                    .IsUnicode(false);

                entity.Property(e => e.RealSsn).HasColumnName("RealSSN");

                entity.Property(e => e.ScrSsnt)
                    .HasMaxLength(38)
                    .IsUnicode(false)
                    .HasColumnName("ScrSSNT");

                entity.Property(e => e.Scrnum).HasColumnName("scrnum");

                entity.Property(e => e.Scrssn).HasColumnName("scrssn");

                entity.Property(e => e.Sta3)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("sta3");
            });

            modelBuilder.Entity<VTreatingSpecialtyRecent3YrsNew>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vTreatingSpecialtyRecent3YrsNew", "shared");

                entity.Property(e => e.Admitday)
                    .HasColumnType("datetime")
                    .HasColumnName("admitday");

                entity.Property(e => e.Bedsecn).HasColumnName("bedsecn");

                entity.Property(e => e.Bsta6a)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("bsta6a");

                entity.Property(e => e.DoB).HasColumnType("datetime");

                entity.Property(e => e.FirstName)
                    .HasMaxLength(75)
                    .IsUnicode(false)
                    .HasColumnName("First_Name");

                entity.Property(e => e.LastName)
                    .HasMaxLength(60)
                    .IsUnicode(false)
                    .HasColumnName("Last_Name");

                entity.Property(e => e.PatientIcn)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("PatientICN");

                entity.Property(e => e.PatientName)
                    .HasMaxLength(120)
                    .IsUnicode(false);

                entity.Property(e => e.RealSsn).HasColumnName("RealSSN");

                entity.Property(e => e.ScrSsnt)
                    .HasMaxLength(38)
                    .IsUnicode(false)
                    .HasColumnName("ScrSSNT");

                entity.Property(e => e.Scrnum).HasColumnName("scrnum");

                entity.Property(e => e.Scrssn).HasColumnName("scrssn");

                entity.Property(e => e.Sta3)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("sta3");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}