// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EF_StoreProc.Models
{
    public partial class sp_TreatingSpecialtiyPatientsResult
    {
        public string bsta6a { get; set; }
        public int? bedsecn { get; set; }
        public DateTime? admitday { get; set; }
        public string ScrSSNT { get; set; }
        public int? scrssn { get; set; }
        public int? scrnum { get; set; }
        public int? RealSSN { get; set; }
        public string Scrssn { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string PatientName { get; set; }
        public string PatientICN { get; set; }
        public DateTime? DoB { get; set; }
    }
}
