// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EF_StoreProc.Models
{
    public partial class spQuestionAnswersResult
    {
        public int EpisodeOfCareID { get; set; }
        public string PatientICNFK { get; set; }
        public int QuestionID { get; set; }
        public string QuestionKey { get; set; }
        public string Question { get; set; }
        [Column("stage name")]
        public string stagename { get; set; }
        public string CodeDescription { get; set; }
        public int AnswerID { get; set; }
        public int AnswerCodeSetFK { get; set; }
        public string CodeValue { get; set; }
        [Column("coded answer")]
        public string codedanswer { get; set; }
        [Column("non-coded text")]
        public string noncodedtext { get; set; }
        public string FacilityID6 { get; set; }
        public string AnswerByUserID { get; set; }
        public DateTime LastUpdate { get; set; }
    }
}
