// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF_StoreProc.Models
{
    public partial class VTreatingSpecialtyPatNoName
    {
        public int? Scrnum { get; set; }
        public int? Scrssn { get; set; }
        public string ScrSsnt { get; set; }
        public int? RealSsn { get; set; }
        public string Bsta6a { get; set; }
        public int? Bedsecn { get; set; }
        public int? CLos { get; set; }
        public DateTime? Admitday { get; set; }
    }
}