// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace IPRehabWebAPI2.Models
{
    public partial class PatientDTOTreatingSpecialty
    {
        [DisplayName("STA6A")]
        public string Sta6a { get; set; }

        [DisplayName("Name")]
        public string Name { get; set; }

        /// <summary>
        /// PTFSSN was from the HealtFactor cube,
        /// and is from SCRSSN in TreatingSpecialty cube during HydrateTreatingSpecialtyPatient() in HydrateDTO.cs
        /// </summary>
        [DisplayName("Scr SSN")]
        public string PTFSSN { get; set; }

        [DisplayName("Real SSN")]
        public string RealSSN { get; set; }

        [DisplayName("ICN")]
        public string PatientICN { get; set; }

        [DisplayName("Date of Birth")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime? DoB { get; set; }

        [DisplayName("Bed Section")]
        public int? Bedsecn { get; set; }

        [DisplayName("Admit Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public List<DateTime> AdmitDates { get; set; }

        [DisplayName("Episode of Care")]
        public List<EpisodeOfCareDTO> CareEpisodes { get; set; }

        public PatientDTOTreatingSpecialty()
        {
            CareEpisodes = new();
            AdmitDates = new();
        }
    }
}