// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;

#nullable disable

namespace IPRehabWebAPI2.Models
{
    public partial class PatientDTOTreatingSpecialty
    {
        [DisplayName("STA6A")]
        public string Sta6a { get; set; }

        [DisplayName("Name")]
        public string Name { get; set; }

        [DisplayName("Scr SSN")]
        public string PTFSSN { get; set; }

        [DisplayName("Real SSN")]
        public string RealSSN { get; set; }

        [DisplayName("ICN")]
        public string PatientICN { get; set; }

        [DisplayName("Date of Birth")]
        public DateTime? DoB { get; set; }

        [DisplayName("Bed Section")]
        public int? Bedsecn { get; set; }

        [DisplayName("Admit Date")]
        public List<DateTime> AdmitDates { get; set; }

        [DisplayName("Episode of Care")]
        public List<EpisodeOfCareDTO> CareEpisodes { get; set; }

        public PatientDTOTreatingSpecialty()
        {
            CareEpisodes = new();
            AdmitDates = new();
        }
    }
}