// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatientModel_TreatingSpecialty
{
    public partial class FactTsallCdw2yrs
    {
        public string Inpatientfeebasissid { get; set; }
        public string Inpatientsid { get; set; }
        public string Bsta6a { get; set; }
        public int? Bedsecn { get; set; }
        public int? Scrnum { get; set; }
        public DateTime? Admitday { get; set; }
        public int? Adtime { get; set; }
        public DateTime? Bsinday { get; set; }
        public int? Bsintime { get; set; }
        public DateTime? Bsoutday { get; set; }
        public int? Bsoutime { get; set; }
        public int? Bssq { get; set; }
        public DateTime? Disday { get; set; }
        public int? Distime { get; set; }
        public int? Distype { get; set; }
        public int? Drgb { get; set; }
        public string Dxlsb { get; set; }
        public string Dxb2 { get; set; }
        public string Dxb3 { get; set; }
        public string Dxb4 { get; set; }
        public string Dxb5 { get; set; }
        public int? Lsb { get; set; }
        public int? Lvb { get; set; }
        public int? Passb { get; set; }
        public int? ScrSsn { get; set; }
        public int? Srtkey { get; set; }
        public int Statyp { get; set; }
        public string Svcconb { get; set; }
        public int? Movement { get; set; }
        public string Source { get; set; }
        public int? ProviderSid { get; set; }
        public int? PrimaryphysicianstaffSid { get; set; }
        public int? AdmitwardlocationSid { get; set; }
        public int? DischargewardlocationSid { get; set; }
        public DateTime? Admitdatetime { get; set; }
        public DateTime? Dischargedatetime { get; set; }
        public DateTime? SpecialtyTransferDateTime { get; set; }
        public DateTime? Bsindatetime { get; set; }
        public DateTime? Bsoutdatetime { get; set; }
        public DateTime? Bsindaynew { get; set; }
        public DateTime? Bsoutdaynew { get; set; }
        public int? Los { get; set; }
        public int? Admission { get; set; }
        public int? Discharge { get; set; }
        public byte GenderKey { get; set; }
        public int? MeansKey { get; set; }
        public int PriorityKey { get; set; }
        public int? EAge { get; set; }
        public string EZipCode { get; set; }
        public int HomeCnty { get; set; }
        public int EEnrstat { get; set; }
        public int? EScper { get; set; }
        public int Drgkey { get; set; }
        public string Icd9key { get; set; }
        public int CenKey { get; set; }
        public string SourceKey { get; set; }
        public int? BsinDayId { get; set; }
        public int? BsoutDayId { get; set; }
        public int? Big { get; set; }
        public double? Bdoc { get; set; }
        public double? Rat { get; set; }
        public decimal? BigMoveId { get; set; }
        public string ScrSsnt { get; set; }
        public int? RealSsn { get; set; }
        public int Oefoifflag { get; set; }
        public string OefoifFlag1 { get; set; }
        public int? FyFacId { get; set; }
        public int MovementId { get; set; }
        public int? Gainingwardlocationsid { get; set; }
        public int? Asihdays { get; set; }
        public int? Racekey { get; set; }
        public int? Ethnicitykey { get; set; }
        public int? Pos { get; set; }
        public int? PcpAdmparentkey { get; set; }
        public int? PcpSta6akey { get; set; }
        public int? Attendingphysicianstaffsid { get; set; }
        public short? SigenderKey { get; set; }
    }
}