// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatientModel_TreatingSpecialty
{
    public partial class FactTsallDayCdw2yrs
    {
        public string Inpatientsid { get; set; }
        public string Bsta6a { get; set; }
        public int? Bedsecn { get; set; }
        public int? Scrnum { get; set; }
        public DateTime Beddate { get; set; }
        public DateTime? Admitday { get; set; }
        public int? Adtime { get; set; }
        public DateTime? Bsinday { get; set; }
        public DateTime? Bsoutday { get; set; }
        public int? Bsoutime { get; set; }
        public int? Bssq { get; set; }
        public DateTime? Disday { get; set; }
        public int? Distime { get; set; }
        public int? Distype { get; set; }
        public int? Drgb { get; set; }
        public string Dxlsb { get; set; }
        public string Dxb2 { get; set; }
        public string Dxb3 { get; set; }
        public string Dxb4 { get; set; }
        public string Dxb5 { get; set; }
        public int? Lsb { get; set; }
        public int? Lvb { get; set; }
        public int? Passb { get; set; }
        public int Sci { get; set; }
        public int? Scrssn { get; set; }
        public int? Srtkey { get; set; }
        public int Statyp { get; set; }
        public string Svcconb { get; set; }
        public int? Movement { get; set; }
        public string Source { get; set; }
        public int? ProviderSid { get; set; }
        public int? PrimaryphysicianstaffSid { get; set; }
        public int? Admitwardlocationsid { get; set; }
        public int? Dischargewardlocationsid { get; set; }
        public DateTime? Admitdatetime { get; set; }
        public DateTime? Dischargedatetime { get; set; }
        public DateTime? Specialtytransferdatetime { get; set; }
        public DateTime? Bsindatetime { get; set; }
        public DateTime? Bsoutdatetime { get; set; }
        public DateTime? Bsindaynew { get; set; }
        public DateTime? Bsoutdaynew { get; set; }
        public int? Los { get; set; }
        public byte GenderKey { get; set; }
        public int? MeansKey { get; set; }
        public int PriorityKey { get; set; }
        public int? EAge { get; set; }
        public string EZipCode { get; set; }
        public int HomeCnty { get; set; }
        public int EEnrstat { get; set; }
        public int? EScper { get; set; }
        public int Drgkey { get; set; }
        public int CenKey { get; set; }
        public int? SourceKey { get; set; }
        public decimal? BigMoveId { get; set; }
        public string ScrSsnt { get; set; }
        public int? Realssn { get; set; }
        public string OefoifFlag { get; set; }
        public int Oefoifflag1 { get; set; }
        public int? FyFacId { get; set; }
        public int? AtimeKey { get; set; }
        public int? DtimeKey { get; set; }
        public decimal? PrPass { get; set; }
        public decimal? PrLeave { get; set; }
        public decimal? PrAsihdays { get; set; }
        public int BedDay { get; set; }
        public int Admission { get; set; }
        public int Discharge { get; set; }
        public int? BedDateId { get; set; }
        public int? Big { get; set; }
        public double? Rat { get; set; }
        public int Transin { get; set; }
        public int Transout { get; set; }
        public int ObsKey { get; set; }
        public int CenDay { get; set; }
        public decimal Gmlos { get; set; }
        public decimal Amlos { get; set; }
        public int? GainingWardlocationSid { get; set; }
        public int? CLos { get; set; }
        public int? Asihdays { get; set; }
        public int? Racekey { get; set; }
        public int? Ethnicitykey { get; set; }
        public int? Pos { get; set; }
        public int? PcpAdmparentkey { get; set; }
        public int? PcpSta6akey { get; set; }
        public int? Attendingphysicianstaffsid { get; set; }
        public decimal? Lsbdim { get; set; }
        public int? Prevlos { get; set; }
        public int? Sigenderkey { get; set; }
    }
}