// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatientModel_TreatingSpecialty;

public partial class PatientDemographic
{
    public string PatientSsn { get; set; }

    public string ScrSsn { get; set; }

    public string Scrnum { get; set; }

    public string Edipi { get; set; }

    public string PatientIcn { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string PatientName { get; set; }

    public string Zip { get; set; }

    public DateTime? DoD { get; set; }

    public DateTime? DoB { get; set; }

    public int? Age { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string Address3 { get; set; }

    public string City { get; set; }

    public string StateProvince { get; set; }

    public string Country { get; set; }

    public string County { get; set; }

    public string PeriodofService { get; set; }

    public int? PercentServiceConnect { get; set; }

    public string InsuranceCoverageFlag { get; set; }

    public int? ReligionKey { get; set; }

    public string Eligibility { get; set; }

    public int? RaceKey { get; set; }

    public int? EthnicityKey { get; set; }

    public int? OefoifFlagKey { get; set; }

    public string Urh { get; set; }

    public string Prio18 { get; set; }

    public byte GenderKey { get; set; }

    public int PriorityKey { get; set; }

    public short MeansKey { get; set; }

    public int Pskey { get; set; }

    public int EligKey { get; set; }

    public short? SigenderKey { get; set; }

    public string TestPatientFlag { get; set; }

    public string CdwpossibleTestPatientFlag { get; set; }

    public int? EnrollmentStatusKey { get; set; }
}