// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatientModel_TreatingSpecialty;

public partial class RptRehabDetails
{
    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string PatientName { get; set; }

    public DateTime? DoB { get; set; }

    public string PatientIcn { get; set; }

    public string Bsta6a { get; set; }

    public string Sta3 { get; set; }

    public int? Bedsecn { get; set; }

    public DateTime? Admitday { get; set; }

    public string ScrSsnt { get; set; }

    public int? Scrssn { get; set; }

    public int? Scrnum { get; set; }

    public string Realssn { get; set; }

    public int? Admission { get; set; }
}