// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using UserModel;

namespace UserModel
{
    public partial interface IMasterreportsContextProcedures
    {
        Task<List<uspVSSCMain_SelectAccessInformationFromNSSDResult>> uspVSSCMain_SelectAccessInformationFromNSSDAsync(string UserName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
