// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using UserModel;

namespace UserModel
{
    public partial class MasterreportsContext
    {
        private IMasterreportsContextProcedures _procedures;

        public virtual IMasterreportsContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new MasterreportsContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IMasterreportsContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<uspVSSCMain_SelectAccessInformationFromNSSDResult>().HasNoKey().ToView(null);
        }
    }

    public partial class MasterreportsContextProcedures : IMasterreportsContextProcedures
    {
        private readonly MasterreportsContext _context;

        public MasterreportsContextProcedures(MasterreportsContext context)
        {
            _context = context;
        }

        public virtual async Task<List<uspVSSCMain_SelectAccessInformationFromNSSDResult>> uspVSSCMain_SelectAccessInformationFromNSSDAsync(string UserName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "UserName",
                    Size = 255,
                    Value = UserName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<uspVSSCMain_SelectAccessInformationFromNSSDResult>("EXEC @returnValue = [Apps].[uspVSSCMain_SelectAccessInformationFromNSSD] @UserName", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
