// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace UserModel
{
  public partial class MasterreportsContext : DbContext
  {
    public MasterreportsContext()
    {
    }

    public MasterreportsContext(DbContextOptions<MasterreportsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<tbl_VSSCMainContent> tbl_VSSCMainContent { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
      modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

      modelBuilder.Entity<tbl_VSSCMainContent>(entity =>
      {
        entity.HasKey(e => e.VSSCMain_ContentID)
                  .HasName("PK_tbl_VSSCMain_ProductList");

        entity.ToTable("tbl_VSSCMainContent", "Apps");

        entity.Property(e => e.CreateDate)
                  .HasColumnType("datetime")
                  .HasDefaultValueSql("(getdate())");

        entity.Property(e => e.CreatedBy).HasMaxLength(500);

        entity.Property(e => e.ModifiedBy).HasMaxLength(500);

        entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

        entity.Property(e => e.ProductName).HasMaxLength(500);

        entity.Property(e => e.ProductTooltip).HasMaxLength(200);

        entity.Property(e => e.ProductURI).HasMaxLength(1000);
      });

      OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
  }
}