// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace UserModel
{
    public partial class tbl_VSSCMainContent
    {
        public long VSSCMain_ContentID { get; set; }
        public long? ProductAreaID { get; set; }
        public long? ProductSubAreaID { get; set; }
        public long? ProductTypeID { get; set; }
        public string ProductName { get; set; }
        public string ProductURI { get; set; }
        public short? ProductType { get; set; }
        public short? ProductLevel { get; set; }
        public string ProductTooltip { get; set; }
        public long? ProductParent { get; set; }
        public long? ProductChild { get; set; }
        public short? ProductSortOrder { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool? IsDeleted { get; set; }
    }
}