// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace UserModel
{
    public partial class uspVSSCMain_SelectAccessInformationFromNSSDResult
    {
        public int UserID { get; set; }
        public int UserIdentity { get; set; }
        public string NTDomain { get; set; }
        public string NTUserName { get; set; }
        public string VISN { get; set; }
        public string Facility { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string appid { get; set; }
        public string acclevid { get; set; }
        public string cprsnssd { get; set; }
        public string sunsetdat { get; set; }
    }
}
