// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace UserModel
{
    public partial class uspVSSCMain_SelectAllProductsResult
    {
        public int ProductID { get; set; }
        public int? RPT_NO { get; set; }
        public string ProductName { get; set; }
        public int? DeveloperEmployeeUserID { get; set; }
        public DateTime? DateOfDevelopment { get; set; }
        public string ProductDescription { get; set; }
        public int? SubProgramAreaID { get; set; }
        public string SubProgramAreaName { get; set; }
        public int? SubjectAreaID { get; set; }
        public string SubjectAreaName { get; set; }
        public string PathOrLinkToProduct { get; set; }
        public string LinkOfDataDef { get; set; }
        public string LinkOfSampleReport { get; set; }
        public int? ServerID { get; set; }
        public string ProductImageURL { get; set; }
        public string ContainsPHI { get; set; }
        public string ProductImageAlt { get; set; }
        public byte[] ProductImageIcon { get; set; }
    }
}
