// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace IPRehabModel
{
    [Table("tblSignature", Schema = "app")]
    [Index(nameof(Signature), Name = "IX_tblSignature", IsUnique = true)]
    public partial class tblSignature
    {
        [Key]
        public int EpisodeCareIDFK { get; set; }
        [Required]
        [MaxLength(50)]
        public byte[] Signature { get; set; }
        [Required]
        [StringLength(100)]
        public string Title { get; set; }
        [Column(TypeName = "date")]
        public DateTime DateInformationProvided { get; set; }
        public TimeSpan? Time { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastUpdate { get; set; }

        [ForeignKey(nameof(EpisodeCareIDFK))]
        [InverseProperty(nameof(tblEpisodeOfCare.tblSignature))]
        public virtual tblEpisodeOfCare EpisodeCareIDFKNavigation { get; set; }
    }
}