// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace IPRehabModel
{
    [Keyless]
    public partial class vFSODPatientDetail
    {
        [StringLength(100)]
        public string VISN { get; set; }
        [StringLength(356)]
        public string Facility { get; set; }
        [StringLength(100)]
        public string District { get; set; }
        [StringLength(356)]
        public string Division { get; set; }
        public int? ADMParent_Key { get; set; }
        public int Sta6aKey { get; set; }
        public int? bedsecn { get; set; }
        [StringLength(137)]
        public string Name { get; set; }
        [StringLength(9)]
        public string PTFSSN { get; set; }
        [StringLength(255)]
        public string FSODSSN { get; set; }
        [Required]
        [StringLength(6)]
        public string FiscalPeriod { get; set; }
        public int FiscalPeriodInt { get; set; }
    }
}