// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace IPRehabModel
{
    [Table("tblAnswer", Schema = "app")]
    [Index(nameof(EpsideOfCareIdfk), nameof(QuestionIdfk), nameof(AnswerCodeSetFk), nameof(AnswerSequenceNumber), Name = "IX_tblAnswer")]
    [Index(nameof(AnswerCodeSetFk), Name = "IX_tblAnswer_AnswerCodeSetFK")]
    [Index(nameof(EpsideOfCareIdfk), Name = "IX_tblAnswer_EpisodeOfCareIDFK")]
    [Index(nameof(QuestionIdfk), Name = "IX_tblAnswer_QuestionIDFK")]
    public partial class TblAnswer
    {
        [Key]
        [Column("EpsideOfCareIDFK")]
        public int EpsideOfCareIdfk { get; set; }
        [Column("QuestionIDFK")]
        public int QuestionIdfk { get; set; }
        [Column("AnswerCodeSetFK")]
        public int AnswerCodeSetFk { get; set; }
        public int AnswerSequenceNumber { get; set; }
        public string Description { get; set; }

        [ForeignKey(nameof(AnswerCodeSetFk))]
        [InverseProperty(nameof(TblCodeSet.TblAnswer))]
        public virtual TblCodeSet AnswerCodeSetFkNavigation { get; set; }
        [ForeignKey(nameof(EpsideOfCareIdfk))]
        [InverseProperty(nameof(TblEpisodeOfCare.TblAnswer))]
        public virtual TblEpisodeOfCare EpsideOfCareIdfkNavigation { get; set; }
        [ForeignKey(nameof(QuestionIdfk))]
        [InverseProperty(nameof(TblQuestion.TblAnswer))]
        public virtual TblQuestion QuestionIdfkNavigation { get; set; }
    }
}