// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IPRehabModel
{
    [Table("tblBranching", Schema = "app")]
    [Index("BranchingName", Name = "IX_tblBranching_Name")]
    [Index("FromQuestionID", "ToQuestionID", "BranchingName", Name = "IX_tblBranching_To_And_From", IsUnique = true)]
    public partial class tblBranching
    {
        [Key]
        public int BranchingID { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string BranchingName { get; set; }
        public int FromQuestionID { get; set; }
        public int ToQuestionID { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string Condition { get; set; }

        [ForeignKey("FromQuestionID")]
        [InverseProperty("tblBranchingFromQuestion")]
        public virtual tblQuestion FromQuestion { get; set; }
        [ForeignKey("ToQuestionID")]
        [InverseProperty("tblBranchingToQuestion")]
        public virtual tblQuestion ToQuestion { get; set; }
    }
}