// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace IPRehabModel
{
    [Table("tblCodeSet", Schema = "app")]
    [Index(nameof(CodeSetParent), nameof(CodeValue), Name = "IX_tblCodeSet", IsUnique = true)]
    public partial class TblCodeSet
    {
        public TblCodeSet()
        {
            InverseCodeSetParentNavigation = new HashSet<TblCodeSet>();
            TblAnswer = new HashSet<TblAnswer>();
            TblQuestionAnswerCodeSetFkNavigation = new HashSet<TblQuestion>();
            TblQuestionFormFkNavigation = new HashSet<TblQuestion>();
            TblQuestionFormSectionFkNavigation = new HashSet<TblQuestion>();
        }

        [Key]
        [Column("CodeSetID")]
        public int CodeSetId { get; set; }
        public int? CodeSetParent { get; set; }
        [Required]
        [StringLength(30)]
        public string CodeValue { get; set; }
        [Required]
        [StringLength(400)]
        public string CodeDescription { get; set; }
        public int? HierarchyType { get; set; }
        public bool? Active { get; set; }
        public int? FyConstraint { get; set; }
        public int? SortOrder { get; set; }
        [StringLength(200)]
        public string Comment { get; set; }

        [ForeignKey(nameof(CodeSetParent))]
        [InverseProperty(nameof(TblCodeSet.InverseCodeSetParentNavigation))]
        public virtual TblCodeSet CodeSetParentNavigation { get; set; }
        [InverseProperty(nameof(TblCodeSet.CodeSetParentNavigation))]
        public virtual ICollection<TblCodeSet> InverseCodeSetParentNavigation { get; set; }
        [InverseProperty("AnswerCodeSetFkNavigation")]
        public virtual ICollection<TblAnswer> TblAnswer { get; set; }
        [InverseProperty(nameof(TblQuestion.AnswerCodeSetFkNavigation))]
        public virtual ICollection<TblQuestion> TblQuestionAnswerCodeSetFkNavigation { get; set; }
        [InverseProperty(nameof(TblQuestion.FormFkNavigation))]
        public virtual ICollection<TblQuestion> TblQuestionFormFkNavigation { get; set; }
        [InverseProperty(nameof(TblQuestion.FormSectionFkNavigation))]
        public virtual ICollection<TblQuestion> TblQuestionFormSectionFkNavigation { get; set; }
    }
}