// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace IPRehabModel
{
  public partial class TblEpisodeOfCare
  {
    public TblEpisodeOfCare()
    {
      TblAnswer = new HashSet<TblAnswer>();
    }

    public virtual TblPatient PatientIcnfkNavigation { get; set; }
    public virtual TblSignature TblSignature { get; set; }
    public virtual ICollection<TblAnswer> TblAnswer { get; set; }
    [Required]
    public int EpisodeOfCareId { get; set; }
    [Required]
    public DateTime OnsetDate { get; set; }
    [Required]
    public DateTime AdmissionDate { get; set; }
    [Required]
    public string PatientIcnfk { get; set; }
    [Required]
    public DateTime LastUpdate { get; set; }
  }
}