// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace IPRehabModel
{
    [Table("tblEpisodeOfCare", Schema = "app")]
    public partial class TblEpisodeOfCare
    {
        [Key]
        [Column("EpisodeOfCareID")]
        public int EpisodeOfCareId { get; set; }
        [Column(TypeName = "date")]
        public DateTime OnsetDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime AdmissionDate { get; set; }
        [Required]
        [Column("PatientICNFK")]
        [StringLength(10)]
        public string PatientIcnfk { get; set; }

        [ForeignKey(nameof(PatientIcnfk))]
        [InverseProperty(nameof(TblPatient.TblEpisodeOfCare))]
        public virtual TblPatient PatientIcnfkNavigation { get; set; }
        [InverseProperty("EpsideOfCareIdfkNavigation")]
        public virtual TblAnswer TblAnswer { get; set; }
        [InverseProperty("EpisodeCareIdfkNavigation")]
        public virtual TblSignature TblSignature { get; set; }
    }
}