// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace IPRehabModel
{
  public partial class TblPatient
  {
    public TblPatient()
    {
      TblEpisodeOfCare = new HashSet<TblEpisodeOfCare>();
    }

    [Required]
    public string Icn { get; set; }
    [Required]
    public string Ien { get; set; }
    [Required]
    public string FirstName { get; set; }
    [Required]
    public string LastName { get; set; }
    public string MiddleName { get; set; }
    [Required]
    public DateTime DateOfBirth { get; set; }
    [Required]
    public string Last4Ssn { get; set; }
    [Required]
    public DateTime LastUpdate { get; set; }

    public virtual ICollection<TblEpisodeOfCare> TblEpisodeOfCare { get; set; }
  }
}