// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace IPRehabModel
{
    [Table("tblQuestionStage", Schema = "app")]
    [Index(nameof(QuestionIDFK), nameof(StageFK), Name = "IX_tblQuestionStage", IsUnique = true)]
    [Index(nameof(QuestionIDFK), Name = "IX_tblQuestionStage_QuestionIdFk")]
    [Index(nameof(StageFK), Name = "IX_tblQuestionStage_StageFk")]
    public partial class tblQuestionStage
    {
        [Key]
        public int Id { get; set; }
        public int QuestionIDFK { get; set; }
        public int StageFK { get; set; }
        [Required]
        public bool? Required { get; set; }
        [StringLength(50)]
        public string StageGroupTitle { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastUpdate { get; set; }

        [ForeignKey(nameof(QuestionIDFK))]
        [InverseProperty(nameof(tblQuestion.tblQuestionStage))]
        public virtual tblQuestion QuestionIDFKNavigation { get; set; }
        [ForeignKey(nameof(StageFK))]
        [InverseProperty(nameof(tblCodeSet.tblQuestionStage))]
        public virtual tblCodeSet StageFKNavigation { get; set; }
    }
}