// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace IPRehabModel
{
   public partial class TblQuestionStage
   {
      public int Id { get; set; }

      public int QuestionIdFk { get; set; }

      public int StageFk { get; set; }

      public bool Required { get; set; }

      public virtual TblQuestion QuestionIdFkNavigation { get; set; }
      public virtual TblCodeSet StageFkNavigation { get; set; }

   }
}