// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IPRehabModel
{
    [Table("tblQuestionInstruction", Schema = "app")]
    [Index("QuestionIDFK", "Order", Name = "IX_tblInstruction", IsUnique = true)]
    public partial class tblQuestionInstruction
    {
        [Key]
        public int InstructionID { get; set; }
        public int QuestionIDFK { get; set; }
        public int? StageCodeSetIDFK { get; set; }
        public int? Order { get; set; }
        public int DisplayLocationFK { get; set; }
        [Required]
        [Unicode(false)]
        public string Instruction { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastUpdate { get; set; }

        [ForeignKey("DisplayLocationFK")]
        [InverseProperty("tblQuestionInstructionDisplayLocationFKNavigation")]
        public virtual tblCodeSet DisplayLocationFKNavigation { get; set; }
        [ForeignKey("QuestionIDFK")]
        [InverseProperty("tblQuestionInstruction")]
        public virtual tblQuestion QuestionIDFKNavigation { get; set; }
        [ForeignKey("StageCodeSetIDFK")]
        [InverseProperty("tblQuestionInstructionStageCodeSetIDFKNavigation")]
        public virtual tblCodeSet StageCodeSetIDFKNavigation { get; set; }
    }
}