// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace IPRehabModel
{
  public partial class TblQuestionStage
  {
    [Required]
    public int Id { get; set; }
    [Required]
    public int QuestionIdFk { get; set; }
    [Required]
    public int StageFk { get; set; }
    [Required]
    public bool Required { get; set; }
    public string StageGroupTitle { get; set; }
    [Required]
    public DateTime LastUpdate { get; set; }

    public virtual TblQuestion QuestionIdFkNavigation { get; set; }
    public virtual TblCodeSet StageFkNavigation { get; set; }
  }
}