// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace IPRehabModel
{
    [Table("tblQuestion", Schema = "app")]
    [Index(nameof(QuestionKey), nameof(GroupTitle), Name = "IX_tblQuestion", IsUnique = true)]
    public partial class tblQuestion
    {
        public tblQuestion()
        {
            tblAnswer = new HashSet<tblAnswer>();
            tblBranchingFromQuestion = new HashSet<tblBranching>();
            tblBranchingToQuestion = new HashSet<tblBranching>();
            tblQuestionInstruction = new HashSet<tblQuestionInstruction>();
            tblQuestionStage = new HashSet<tblQuestionStage>();
        }

        [Key]
        public int QuestionID { get; set; }
        [Required]
        [StringLength(20)]
        public string QuestionKey { get; set; }
        public int? Order { get; set; }
        [StringLength(200)]
        public string QuestionSection { get; set; }
        [Required]
        [StringLength(1000)]
        public string Question { get; set; }
        [StringLength(50)]
        public string GroupTitle { get; set; }
        public int AnswerCodeSetFK { get; set; }
        public bool? BranchingPoint { get; set; }
        public bool? MultiChoice { get; set; }
        public bool? Active { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastUpdate { get; set; }

        [ForeignKey(nameof(AnswerCodeSetFK))]
        [InverseProperty(nameof(tblCodeSet.tblQuestion))]
        public virtual tblCodeSet AnswerCodeSetFKNavigation { get; set; }
        [InverseProperty("QuestionIDFKNavigation")]
        public virtual ICollection<tblAnswer> tblAnswer { get; set; }
        [InverseProperty(nameof(tblBranching.FromQuestion))]
        public virtual ICollection<tblBranching> tblBranchingFromQuestion { get; set; }
        [InverseProperty(nameof(tblBranching.ToQuestion))]
        public virtual ICollection<tblBranching> tblBranchingToQuestion { get; set; }
        [InverseProperty("QuestionIDFKNavigation")]
        public virtual ICollection<tblQuestionInstruction> tblQuestionInstruction { get; set; }
        [InverseProperty("QuestionIDFKNavigation")]
        public virtual ICollection<tblQuestionStage> tblQuestionStage { get; set; }
    }
}