// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace IPRehabModel
{
    public partial class TblQuestionInstruction
    {
        public int InstructionId { get; set; }
        public int QuestionIdfk { get; set; }
        public int? Order { get; set; }
        public string Instruction { get; set; }

        public virtual TblQuestion QuestionIdfkNavigation { get; set; }
    }
}