// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace IPRehabModel
{
    [Table("tblQuestionInstruction", Schema = "app")]
    [Index(nameof(QuestionIdfk), nameof(Order), Name = "IX_tblInstruction", IsUnique = true)]
    public partial class TblQuestionInstruction
    {
        [Key]
        [Column("InstructionID")]
        public int InstructionId { get; set; }
        [Column("QuestionIDFK")]
        public int QuestionIdfk { get; set; }
        public int? Order { get; set; }
        [Required]
        public string Instruction { get; set; }

        [ForeignKey(nameof(QuestionIdfk))]
        [InverseProperty(nameof(TblQuestion.TblQuestionInstruction))]
        public virtual TblQuestion QuestionIdfkNavigation { get; set; }
    }
}