// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IPRehabModel
{
    [Table("tblQuestion", Schema = "app")]
    public partial class tblQuestion
    {
        public tblQuestion()
        {
            tblAnswer = new HashSet<tblAnswer>();
            tblBranchingFromQuestion = new HashSet<tblBranching>();
            tblBranchingToQuestion = new HashSet<tblBranching>();
            tblQuestionInstruction = new HashSet<tblQuestionInstruction>();
            tblQuestionMeasure = new HashSet<tblQuestionMeasure>();
        }

        [Key]
        public int QuestionID { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string QuestionKey { get; set; }
        public int? Order { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string QuestionSection { get; set; }
        [Required]
        [StringLength(1000)]
        [Unicode(false)]
        public string Question { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string GroupTitle { get; set; }
        public int AnswerCodeSetFK { get; set; }
        public bool? BranchingPoint { get; set; }
        public bool? MultiChoice { get; set; }
        public bool? Active { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LastUpdate { get; set; }

        [ForeignKey("AnswerCodeSetFK")]
        [InverseProperty("tblQuestion")]
        public virtual tblCodeSet AnswerCodeSetFKNavigation { get; set; }
        [InverseProperty("QuestionIDFKNavigation")]
        public virtual ICollection<tblAnswer> tblAnswer { get; set; }
        [InverseProperty("FromQuestion")]
        public virtual ICollection<tblBranching> tblBranchingFromQuestion { get; set; }
        [InverseProperty("ToQuestion")]
        public virtual ICollection<tblBranching> tblBranchingToQuestion { get; set; }
        [InverseProperty("QuestionIDFKNavigation")]
        public virtual ICollection<tblQuestionInstruction> tblQuestionInstruction { get; set; }
        [InverseProperty("QuestionIDFKNavigation")]
        public virtual ICollection<tblQuestionMeasure> tblQuestionMeasure { get; set; }
    }
}