// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace IPRehabModel
{
  public partial class TblSignature
  {
    [Required]
    public int EpisodeCareIdfk { get; set; }
    [Required]
    public byte[] Signature { get; set; }
    [Required]
    public string Title { get; set; }
    [Required]
    public DateTime DateInformationProvided { get; set; }
    public TimeSpan? Time { get; set; }
    [Required]
    public DateTime LastUpdate { get; set; }
    public virtual TblEpisodeOfCare EpisodeCareIdfkNavigation { get; set; }
  }
}