// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace IPRehabModel
{
    public partial class TblSignature
    {
        public int EpisodeCareIdfk { get; set; }
        public byte[] Signature { get; set; }
        public string Title { get; set; }
        public DateTime DateInformationProvided { get; set; }
        public TimeSpan? Time { get; set; }

        public virtual TblEpisodeOfCare EpisodeCareIdfkNavigation { get; set; }
    }
}