// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace IPRehabModel
{
    [Keyless]
    public partial class VCodeSetHierarchy
    {
        [StringLength(400)]
        public string Hierarchy { get; set; }
        [Column("CHILD ID")]
        public int ChildId { get; set; }
        [Required]
        [Column("CHILD value")]
        [StringLength(30)]
        public string ChildValue { get; set; }
        [Required]
        [Column("CHILD description")]
        [StringLength(400)]
        public string ChildDescription { get; set; }
        [Column("PARENT ID")]
        public int? ParentId { get; set; }
        [Column("PARENT value")]
        [StringLength(30)]
        public string ParentValue { get; set; }
        [Column("PARENT description")]
        [StringLength(400)]
        public string ParentDescription { get; set; }
        [Column("PARENT comment")]
        [StringLength(200)]
        public string ParentComment { get; set; }
        [Column("GRAND ID")]
        public int? GrandId { get; set; }
        [Column("GRAND value")]
        [StringLength(30)]
        public string GrandValue { get; set; }
        [Column("GRAND description")]
        [StringLength(400)]
        public string GrandDescription { get; set; }
        [Column("GREAT ID")]
        public int? GreatId { get; set; }
        [Column("GREAT value")]
        [StringLength(30)]
        public string GreatValue { get; set; }
        [Column("GREAT description")]
        [StringLength(400)]
        public string GreatDescription { get; set; }
        [Column("ANCESTOR ID")]
        public int? AncestorId { get; set; }
        [Column("ANCESTOR value")]
        [StringLength(30)]
        public string AncestorValue { get; set; }
        [Column("ANCESTOR description")]
        [StringLength(400)]
        public string AncestorDescription { get; set; }
        [Column("ANTIQUITY ID")]
        public int? AntiquityId { get; set; }
        [Column("ANTIQUITY value")]
        [StringLength(30)]
        public string AntiquityValue { get; set; }
        [Column("ANTIQUITY description")]
        [StringLength(400)]
        public string AntiquityDescription { get; set; }
    }
}