// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace IPRehabModel
{
    [Keyless]
    public partial class vCodeSetHierarchy
    {
        [StringLength(400)]
        public string Hierarchy { get; set; }
        [Column("CHILD ID")]
        public int CHILD_ID { get; set; }
        [Required]
        [Column("CHILD value")]
        [StringLength(30)]
        public string CHILD_value { get; set; }
        [Required]
        [Column("CHILD description")]
        [StringLength(400)]
        public string CHILD_description { get; set; }
        [Column("CHILD comment")]
        [StringLength(200)]
        public string CHILD_comment { get; set; }
        [Column("PARENT ID")]
        public int? PARENT_ID { get; set; }
        [Column("PARENT value")]
        [StringLength(30)]
        public string PARENT_value { get; set; }
        [Column("PARENT description")]
        [StringLength(400)]
        public string PARENT_description { get; set; }
        [Column("PARENT comment")]
        [StringLength(200)]
        public string PARENT_comment { get; set; }
        [Column("GRAND ID")]
        public int? GRAND_ID { get; set; }
        [Column("GRAND value")]
        [StringLength(30)]
        public string GRAND_value { get; set; }
        [Column("GRAND description")]
        [StringLength(400)]
        public string GRAND_description { get; set; }
        [Column("GRAND comment")]
        [StringLength(200)]
        public string GRAND_comment { get; set; }
        [Column("GREAT ID")]
        public int? GREAT_ID { get; set; }
        [Column("GREAT value")]
        [StringLength(30)]
        public string GREAT_value { get; set; }
        [Column("GREAT description")]
        [StringLength(400)]
        public string GREAT_description { get; set; }
        [Column("GREAT comment")]
        [StringLength(200)]
        public string GREAT_comment { get; set; }
        [Column("ANCESTOR ID")]
        public int? ANCESTOR_ID { get; set; }
        [Column("ANCESTOR value")]
        [StringLength(30)]
        public string ANCESTOR_value { get; set; }
        [Column("ANCESTOR description")]
        [StringLength(400)]
        public string ANCESTOR_description { get; set; }
        [Column("ANCESTER comment")]
        [StringLength(200)]
        public string ANCESTER_comment { get; set; }
        [Column("ANTIQUITY ID")]
        public int? ANTIQUITY_ID { get; set; }
        [Column("ANTIQUITY value")]
        [StringLength(30)]
        public string ANTIQUITY_value { get; set; }
        [Column("ANTIQUITY description")]
        [StringLength(400)]
        public string ANTIQUITY_description { get; set; }
        [Column("ANTIQUITY comment")]
        [StringLength(200)]
        public string ANTIQUITY_comment { get; set; }
    }
}