// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace IPRehabModel
{
    public partial class VCodeSetHierarchy
    {
        public string Hierarchy { get; set; }
        public int ChildId { get; set; }
        public string ChildValue { get; set; }
        public string ChildDescription { get; set; }
        public int? ParentId { get; set; }
        public string ParentValue { get; set; }
        public string ParentDescription { get; set; }
        public string ParentComment { get; set; }
        public int? GrandId { get; set; }
        public string GrandValue { get; set; }
        public string GrandDescription { get; set; }
        public int? GreatId { get; set; }
        public string GreatValue { get; set; }
        public string GreatDescription { get; set; }
        public int? AncestorId { get; set; }
        public string AncestorValue { get; set; }
        public string AncestorDescription { get; set; }
        public int? AntiquityId { get; set; }
        public string AntiquityValue { get; set; }
        public string AntiquityDescription { get; set; }
    }
}