// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace IPRehabModel
{
    public partial class VQuestionStandardChoicesCondensed
    {
        public int QuestionId { get; set; }
        public string QuestionKey { get; set; }
        public int? Order { get; set; }
        public string Question { get; set; }
        public int CodeSet { get; set; }
        public string ValidChoice { get; set; }
        public string ChoiceCode { get; set; }
        public string CodeSetComment { get; set; }
    }
}