// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace IPRehabModel
{
    [Keyless]
    public partial class VQuestionStandardChoicesCondensed
    {
        [Column("QuestionID")]
        public int QuestionId { get; set; }
        [Required]
        [StringLength(20)]
        public string QuestionKey { get; set; }
        [Column("order")]
        public int? Order { get; set; }
        [Required]
        public string Question { get; set; }
        [Column("Code Set")]
        public int CodeSet { get; set; }
        [Column("Valid Choice")]
        [StringLength(400)]
        public string ValidChoice { get; set; }
        [Column("Choice Code")]
        [StringLength(30)]
        public string ChoiceCode { get; set; }
        [Column("Code Set Comment")]
        [StringLength(200)]
        public string CodeSetComment { get; set; }
    }
}