// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace IPRehabModel
{
    [Keyless]
    public partial class vQuestionStandardChoices_Condensed
    {
        [StringLength(30)]
        public string Form { get; set; }
        [StringLength(30)]
        public string Section { get; set; }
        [Required]
        [StringLength(20)]
        public string QuestionKey { get; set; }
        public int? order { get; set; }
        [Required]
        public string Question { get; set; }
        [Column("Code Set")]
        public int Code_Set { get; set; }
        [Column("Valid Choice")]
        [StringLength(400)]
        public string Valid_Choice { get; set; }
        [Column("Choice Code")]
        [StringLength(30)]
        public string Choice_Code { get; set; }
        [Column("Code Value Comment")]
        [StringLength(200)]
        public string Code_Value_Comment { get; set; }
        [Column("PARENT comment")]
        [StringLength(200)]
        public string PARENT_comment { get; set; }
        [Column("GRAND comment")]
        [StringLength(200)]
        public string GRAND_comment { get; set; }
        [Column("GREAT comment")]
        [StringLength(200)]
        public string GREAT_comment { get; set; }
        [Column("ANTIQUITY Comment")]
        [StringLength(200)]
        public string ANTIQUITY_Comment { get; set; }
    }
}