// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IPRehabModel
{
    [Keyless]
    public partial class vTreatingSpecialtyRecent3Yrs
    {
        [StringLength(60)]
        [Unicode(false)]
        public string Last_Name { get; set; }
        [StringLength(75)]
        [Unicode(false)]
        public string First_Name { get; set; }
        [StringLength(120)]
        [Unicode(false)]
        public string PatientName { get; set; }
        public int? scrssn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DoB { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string PatientICN { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string bsta6a { get; set; }
        public int? bedsecn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? admitday { get; set; }
    }
}