// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PatientModel
{
    public partial class DmhealthfactorsContext : DbContext
    {
        public DmhealthfactorsContext()
        {
        }

        public DmhealthfactorsContext(DbContextOptions<DmhealthfactorsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<FSODPatient> FSODPatient { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FSODPatient>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("FSODPatientDetailFY22Q3", "FSOD");

                entity.Property(e => e.District)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Division).HasMaxLength(356);

                entity.Property(e => e.FSODSSN).HasMaxLength(9);

                entity.Property(e => e.Facility).HasMaxLength(356);

                entity.Property(e => e.FiscalPeriod)
                    .IsRequired()
                    .HasMaxLength(6)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .HasMaxLength(137)
                    .IsUnicode(false);

                entity.Property(e => e.PTFSSN)
                    .HasMaxLength(9)
                    .IsUnicode(false);

                entity.Property(e => e.VISN)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}