// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PatientModel
{
    public partial class FSODPatient
    {
        public string VISN { get; set; }
        public string Facility { get; set; }
        public string District { get; set; }
        public string Division { get; set; }
        public int? ADMParent_Key { get; set; }
        public int Sta6aKey { get; set; }
        public int? bedsecn { get; set; }
        public string Name { get; set; }
        public string PTFSSN { get; set; }
        public string FSODSSN { get; set; }
        public string FiscalPeriod { get; set; }
        public int FiscalPeriodInt { get; set; }
    }
}